### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by SimonLefort** [thetarkus/docker-funkwhale#14]
Hello,

**Describe the bug**
The container restarting in loop with this error in logs : 
`standard_init_linux.go:207: exec user process caused "exec format error"`

**Logs**
Only this line, multiple time : 

```
# Stdout
`standard_init_linux.go:207: exec user process caused "exec format error"`

# Logs are located in the `/var/log/funkwhale/` directory.
Error response from daemon: Container 20b36815cb906cdbdc6bd1f94aebcf3c601ca09fd932225f523baafaf315e073 is restarting, wait until the container is running
```

**Options**
Submit your command options and arguments like volumes, environment variables, and ports.

```
funkwhale@odroid:~$ export FUNKWHALE_VERSION="0.18.1"

funkwhale@odroid:~$ ls -al
total 44
drwxr-xr-x 5 funkwhale funkwhale 4096 Feb  3 16:23 .
drwxr-xr-x 5 root      root      4096 Feb  3 15:29 ..
-rw------- 1 funkwhale funkwhale  685 Feb  3 16:21 .bash_history
-rw-r--r-- 1 funkwhale funkwhale  220 Aug 31  2015 .bash_logout
-rw-r--r-- 1 funkwhale funkwhale 3771 Aug 31  2015 .bashrc
-rw-r--r-- 1 funkwhale funkwhale  163 Feb  3 16:22 .env
drwx------ 3 funkwhale funkwhale 4096 Feb  3 16:22 .local
-rw-r--r-- 1 funkwhale funkwhale  807 Apr  4  2018 .profile
-rw------- 1 funkwhale funkwhale 1024 Feb  3 15:30 .rnd
drwxr-xr-x 2 root      root      4096 Feb  3 15:33 data
drwxr-xr-x 2 funkwhale funkwhale 4096 Feb  3 16:23 music

funkwhale@odroid:~$ cat .env 
FUNKWHALE_HOSTNAME=funkwhale.local
FUNKWHALE_PROTOCOL=http
DJANGO_SECRET_KEY=ee4bf327917c7ab5db85a5bae52548bf155ac5be359aab55cfd3dc14ef405fb752bf241c0650d32f75b3e6ae5f

funkwhale@odroid:~$ docker run --name=funkwhale --restart=unless-stopped --env-file=/srv/funkwhale/.env -v /srv/funkwhale/data:/data -v /srv/funkwhale/music:/music:ro -e PUID=$UID -e PGID=$GID -p 5000:80 -d funkwhale/all-in-one:$FUNKWHALE_VERSION
2160357be55e0e63c256c641fbb5867711cc15efc7788ba07a5d149ef4f743d
```

**System information**
 - OS: Ubuntu bionic on ARM (odroid-xu3)
 - Run tool: only Docker
 - Docker version: 18.09.1, build 4c52b90
 - Tag: 0.18.1

**Additional context**
Nothing special, I follow these instructions : https://docs.funkwhale.audio/installation/docker.html#docker-mono-container

Thanks in advance

**Comment by thetarkus** [comment]
Hi,
I believe that the funkwhale image must be built using ARM to be able to run it with an ARM device.  
@EliotBerriot most likely runs x86_64 on his build server.

You can manually [build the image](https://github.com/thetarkus/docker-funkwhale#build-this-image) on your odroid and it should work on the ARM architecture.

**Comment by SimonLefort** [comment]
Thanks, I didn't try to build the image... :-O 

There is what I just did :
 
```
$ image_name="funkwhale-arm"
$ version="develop" #"0.18.1" should works too
$ git clone https://github.com/thetarkus/docker-funkwhale.git
$ cd docker-funkwhale/
$ ./scripts/download-artifact.sh src/ $version build_front
$ ./scripts/download-artifact.sh src/ $version build_api
$ ./scripts/download-nginx-template.sh src/ $version
$ docker build -t $image_name:$version .
```

Image is building... :-)

**Comment by thetarkus** [comment]
I forgot to mention that you need to set the build argument `arch` to your architecture.
The argument could either be `arm` or `armhf`, if one doesn't work try the other.
```sh
docker build --build-arg arch=arm -t $image_name:$version .
```

Let me know if this works

**Comment by SimonLefort** [comment]
Hello! 

I can build and launch the image. I have a 500 error but this is another problem... I am not sure if I open a new issue here or directly in the funkwhale's issues. :-/ 

The problem : 
```
$ image_name="funkwhale-0.18.1-arm"

$ version="0.18.1"

$ docker build  --build-arg arch=arm -t $image_name:$version .
funkwhale@odroid:/home/simon/docker-funkwhale$ docker run --name=funkwhale --restart=unless-stopped --env-file=/srv/funkwhale/.env -v /srv/funkwhale/data:/data -v /srv/funkwhale/music:/music:ro -e PUID=$UID -e PGID=$GID -p 5000:80 -d funkwhale-0.18.1-arm:0.18.1

funkwhale@odroid:/home/simon/docker-funkwhale$ docker ps
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS              PORTS                  NAMES
391aae331bda        funkwhale-0.18.1-arm:0.18.1   "/init"             6 minutes ago       Up 6 minutes        0.0.0.0:5000->80/tcp   funkwhale

funkwhale@odroid:/home/simon/docker-funkwhale$ docker logs funkwhale

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "./funkwhale_api/common/middleware.py", line 135, in __call__
    return serve_spa(request)
  File "./funkwhale_api/common/middleware.py", line 22, in serve_spa
    html = get_spa_html(settings.FUNKWHALE_SPA_HTML_ROOT)
  File "./funkwhale_api/common/middleware.py", line 66, in get_spa_html
    verify=settings.EXTERNAL_REQUESTS_VERIFY_SSL,
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='funk.local', port=80): Max retries exceeded with url: /front/index.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb3b1a590>: Failed to establish a new connection: [Errno -2] Name does not resolve',))
```

**Comment by SimonLefort** [comment]
Same problem on my laptop.

**Comment by EliotBerriot** [comment]
@SimonLefort yeah, that's a bit annoying :/ Can you try providing the following env variable? `-e FUNKWHALE_SPA_HTML_ROOT=http://localhost/front/`?

If it works, we'll have to find a fix, basically, the hostname must be reachable from inside the container, which is usually not an issue, but in the case of this image, we could probably hardcode this env var in the dockerfile :)

**Comment by SimonLefort** [comment]
It works! :-) 

`funkwhale@mycomputer:~$ docker run --name=funkwhale --restart=unless-stopped --env-file=/srv/funkwhale/.env -v /srv/funkwhale/data:/data -e FUNKWHALE_SPA_HTML_ROOT=http://localhost/front/ -v /path/to/my/Musique:/music:ro -e PUID=$UID -e PGID=$GID -p 5001:80 -d funkwhale-0.18.1:0.18.1`

**Comment by EliotBerriot** [comment]
Ok, I'll update the dockerfile then :)

**Comment by SimonLefort** [comment]
Because it could help someone, one day : 
[https://simonlefort.be/wiki/doku.php?id=funkwhale](I explain how I build the image and install on my odroid)

:-)
