### ISSUE TITLE
DB not created at start

### ISSUE THREAD

**Issue by LuxAetern** [thetarkus/docker-funkwhale#2]
there seams to be some error at the db creation
the commands for the psql are not recognized and split up
Instead of:
`psql -c 'GRANT ALL PRIVILEGES ON DATABASE funkwhale TO funkwhale;`  
it tries to execute the following:
```
psql -c 'GRANT;
psql -c 'ALL;
psql -c 'PRIVILEGES;
psql -c 'ON;
psql -c 'DATABASE;
and so on...
```
I am using the docker with unraid and the CA Template
Any Idea how to fix this?

**Comment by onedr0p** [comment]
I am running this just fine. Are you sure you're pulling down the latest image?

**Comment by LuxAetern** [comment]
i used the Unraid Template from thetarkus (he pulled it down already...)
the Docker command is the following:
```
 docker run -d --name='Funkwhale' --net='bridge' -e 'PUID'='99' -e 'PGID'='100' -e 'FUNKWHALE_URL'='funkwhale.example.org' -p '3030:80/tcp' -v '/some/path/funkwhale':'/data':'rw' -v '/some/path/music/':'/music':'ro' 'thetarkus/funkwhale' 
```
## Importend Part of the log:
```
...
stopped waiting
createdb: could not connect to database template1: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
psql: warning: extra command-line argument "ON" ignored
psql: warning: extra command-line argument "DATABASE" ignored
psql: warning: extra command-line argument "funkwhale" ignored
psql: warning: extra command-line argument "TO" ignored
psql: warning: extra command-line argument "funkwhale;" ignored
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
psql: warning: extra command-line argument "WITH" ignored
psql: warning: extra command-line argument "SUPERUSER;" ignored
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
### Heres the complete log (long)
```
ErrorWarningSystemArrayLogin

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-database: applying...
[fix-attrs.d] 10-database: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-users: executing...
chmod: /app/api/staticfiles: No such file or directory
chmod: /data/data: No such file or directory
[cont-init.d] 10-users: exited 1.
[cont-init.d] 20-database: executing...
The files belonging to this database system will be owned by user "funkwhale".
This user must also own the server process.

The database cluster will be initialized with locales
COLLATE: C
CTYPE: C.UTF-8
MESSAGES: C
MONETARY: C
NUMERIC: C
TIME: C
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /data/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
sh: locale: not found
2019-01-12 00:11:47.413 CET [274] WARNING: no usable system locales were found
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success.


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2019-01-12 00:11:53.060 CET [279] LOG: listening on IPv4 address "127.0.0.1", port 5432
2019-01-12 00:11:53.060 CET [279] LOG: could not bind IPv6 address "::1": Address not available
2019-01-12 00:11:53.060 CET [279] HINT: Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2019-01-12 00:11:53.063 CET [279] FATAL: could not open lock file "/run/postgresql/.s.PGSQL.5432.lock": Permission denied
2019-01-12 00:11:53.063 CET [279] LOG: database system is shut down
pg_ctl: could not start server
Examine the log output.
stopped waiting
createdb: could not connect to database template1: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
psql: warning: extra command-line argument "ON" ignored
psql: warning: extra command-line argument "DATABASE" ignored
psql: warning: extra command-line argument "funkwhale" ignored
psql: warning: extra command-line argument "TO" ignored
psql: warning: extra command-line argument "funkwhale;" ignored
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
psql: warning: extra command-line argument "WITH" ignored
psql: warning: extra command-line argument "SUPERUSER;" ignored
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
[cont-init.d] 20-database: exited 2.
[cont-init.d] 30-webserver: executing...
[cont-init.d] 30-webserver: exited 0.
[cont-init.d] 40-funkwhale: executing...
collecting static files
Copying '/app/api/funkwhale_api/static/css/project.css'
Copying '/app/api/funkwhale_api/static/images/favicon.ico'
Copying '/app/api/funkwhale_api/static/js/project.js'
Copying '/app/api/funkwhale_api/static/music/sample1.ogg'
Copying '/app/api/funkwhale_api/static/sass/project.scss'
Copying '/usr/lib/python3.6/site-packages/channels/static/channels/js/websocketbridge.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/autocomplete.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/fonts.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/responsive.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/responsive_rtl.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/vendor/select2/LICENSE-SELECT2.md'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/vendor/select2/select2.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/css/vendor/select2/select2.min.css'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/fonts/README.txt'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/LICENSE'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/README.txt'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-no.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/search.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/autocomplete.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/cancel.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/change_form.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/popup_response.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/prepopulate_init.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/LICENSE-SELECT2.md'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/select2.full.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/select2.full.min.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/ar.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/az.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/bg.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/ca.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/cs.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/da.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/de.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/el.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/en.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/es.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/et.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/eu.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/fa.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/fi.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/fr.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/gl.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/he.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/hi.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/hr.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/hu.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/id.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/is.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/it.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/ja.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/km.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/ko.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/lt.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/lv.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/mk.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/ms.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/nb.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/nl.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/pl.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/pt-BR.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/pt.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/ro.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/ru.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/sk.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/sr-Cyrl.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/sr.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/sv.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/th.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/tr.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/uk.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/vi.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/zh-CN.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/select2/i18n/zh-TW.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
Copying '/usr/lib/python3.6/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/css/bootstrap-tweaks.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/css/bootstrap.min.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/css/default.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/css/prettify.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/css/base.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/css/bootstrap-theme.min.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/css/bootstrap.min.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/css/font-awesome-4.0.3.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/css/highlight.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/css/jquery.json-view.min.css'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.eot'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.svg'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.ttf'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/fontawesome-webfont.woff'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.eot'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.svg'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.ttf'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/fonts/glyphicons-halflings-regular.woff2'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/img/favicon.ico'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/img/grid.png'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/js/api.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/js/bootstrap.min.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/js/highlight.pack.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/js/jquery-1.10.2.min.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/docs/js/jquery.json-view.min.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.eot'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.svg'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.ttf'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/fonts/glyphicons-halflings-regular.woff2'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings-white.png'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings.png'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/img/grid.png'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/ajax-form.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/bootstrap.min.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/coreapi-0.1.1.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/csrf.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/default.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/jquery-1.12.4.min.js'
Copying '/usr/lib/python3.6/site-packages/rest_framework/static/rest_framework/js/prettify-min.js'
Copying '/usr/lib/python3.6/site-packages/versatileimagefield/static/versatileimagefield/css/versatileimagefield-bootstrap3.css'
Copying '/usr/lib/python3.6/site-packages/versatileimagefield/static/versatileimagefield/css/versatileimagefield-djangoadmin.css'
Copying '/usr/lib/python3.6/site-packages/versatileimagefield/static/versatileimagefield/css/versatileimagefield.css'
Copying '/usr/lib/python3.6/site-packages/versatileimagefield/static/versatileimagefield/js/versatileimagefield.js'

169 static files copied to '/app/api/staticfiles'.
running data migration
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
self.connect()
File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
self.connection = self.get_new_connection(conn_params)
File "/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
connection = Database.connect(**conn_params)
File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "manage.py", line 20, in <module>
execute_from_command_line(sys.argv)
File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
utility.execute()
File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
output = self.handle(*args, **options)
File "/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 79, in handle
executor = MigrationExecutor(connection, self.migration_progress_callback)
File "/usr/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
self.loader = MigrationLoader(self.connection)
File "/usr/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
self.build_graph()
File "/usr/lib/python3.6/site-packages/django/db/migrations/loader.py", line 207, in build_graph
self.applied_migrations = recorder.applied_migrations()
File "/usr/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
if self.has_table():
File "/usr/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
return self._cursor()
File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
self.ensure_connection()
File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
self.connect()
File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
self.connect()
File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
self.connection = self.get_new_connection(conn_params)
File "/usr/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
connection = Database.connect(**conn_params)
File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

[cont-init.d] 40-funkwhale: exited 1.
[cont-init.d] done.
[services.d] starting services
337:C 11 Jan 23:11:56.707 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
337:C 11 Jan 23:11:56.707 # Redis version=4.0.11, bits=64, commit=bca38d14, modified=0, pid=337, just started
337:C 11 Jan 23:11:56.708 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
337:M 11 Jan 23:11:56.710 * Running mode=standalone, port=6379.
337:M 11 Jan 23:11:56.710 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
337:M 11 Jan 23:11:56.710 # Server initialized
337:M 11 Jan 23:11:56.710 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
337:M 11 Jan 23:11:56.710 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
337:M 11 Jan 23:11:56.710 * Ready to accept connections
[services.d] done.
```

**Comment by LuxAetern** [comment]
The Settings are pretty standard in Unraid (99/100) and its also what his Template uses
Normaly these work fine...
I think i will just wait till thetarkus enables his template again, maybe it will work then
Thanks anyway
