### ISSUE TITLE
[1.1.3] Exception in worker process

### ISSUE THREAD

**Issue by Angelinsky7** [thetarkus/docker-funkwhale#61]
Hi,
after a pull of the latest image on a working config, i've got this exception : 

```
[2021-08-02 14:01:03 +0000] [372] [INFO] Starting gunicorn 20.0.4
[2021-08-02 14:01:03 +0000] [372] [INFO] Listening at: http://127.0.0.1:8000 (372)
[2021-08-02 14:01:03 +0000] [372] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2021-08-02 14:01:03 +0000] [375] [INFO] Booting worker with pid: 375
2021-08-02 14:01:05,035 funkwhale_api.config INFO     Running with the following plugins enabled: funkwhale_api.contrib.scrobbler, funkwhale_api.contrib.listenbrainz
[2021-08-02 14:01:06 +0000] [375] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.7/site-packages/uvicorn/workers.py", line 62, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/api/config/asgi.py", line 8, in <module>
    django.setup()
  File "/usr/lib/python3.7/site-packages/django/__init__.py", line 22, in setup
    '/' if settings.FORCE_SCRIPT_NAME is None else settings.FORCE_SCRIPT_NAME
  File "/usr/lib/python3.7/site-packages/django/urls/base.py", line 105, in set_script_prefix
    _prefixes.value = prefix
  File "/usr/lib/python3.7/site-packages/asgiref/local.py", line 113, in __setattr__
    storage = self._get_storage()
  File "/usr/lib/python3.7/site-packages/asgiref/local.py", line 83, in _get_storage
    context_obj = self._get_context_id()
  File "/usr/lib/python3.7/site-packages/asgiref/local.py", line 51, in _get_context_id
    from .sync import AsyncToSync, SyncToAsync
  File "/usr/lib/python3.7/site-packages/asgiref/sync.py", line 304, in <module>
    class SyncToAsync:
  File "/usr/lib/python3.7/site-packages/asgiref/sync.py", line 328, in SyncToAsync
    loop = get_running_loop()
RuntimeError: no running event loop
[2021-08-02 14:01:06 +0000] [375] [INFO] Worker exiting (pid: 375)
[2021-08-02 14:01:07 +0000] [372] [INFO] Shutting down: Master
[2021-08-02 14:01:07 +0000] [372] [INFO] Reason: Worker failed to boot.
```

```
Pulling funkwhale (funkwhale/all-in-one:latest)...
latest: Pulling from funkwhale/all-in-one
Digest: sha256:493e3de9d1d47f4428c33eaa33ebb8a8666950e8facdaa8e435a32b824a0c058
Status: Image is up to date for funkwhale/all-in-one:latest
```

my docker-compose.yml : 

```
version: "2"
services:
  funkwhale:
    restart: always
    image: funkwhale/all-in-one
    environment:
      - FUNKWHALE_HOSTNAME=HOSTNAME
      - FUNKWHALE_PROTOCOL=https
      - NGINX_MAX_BODY_SIZE=100M
      - FUNKWHALE_API_IP=127.0.0.1
      - FUNKWHALE_API_PORT=5123
      - DJANGO_SECRET_KEY=KEY
      - NESTED_PROXY=1
      - EMAIL_CONFIG=EMAIL_CONFIG
      - DEFAULT_FROM_EMAIL=EMAIL
      - MUSIC_DIRECTORY_PATH=/music
      - MUSIC_DIRECTORY_SERVE_PATH=/srv/projects/funkwhale/musics
    volumes:
      - ./data:/data
      - /srv/projects/funkwhale/musics:/music:ro
    ports:
      - "5123:80"
```

is there a update procedure that i missed ?

**Comment by Angelinsky7** [comment]
i can confirm it's working with `funkwhale/all-in-one:1.1.2`
